# Generated by Django 4.2.4 on 2023-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_id', models.IntegerField()),
                ('customar_name', models.CharField(max_length=50)),
                ('customar_email', models.EmailField(max_length=30)),
                ('payment', models.IntegerField()),
                ('product', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('text_aria', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=20)),
                ('re_password', models.CharField(max_length=20)),
                ('checkedbox', models.CharField(max_length=20)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('make_seor', models.BooleanField()),
            ],
        ),
    ]
